name: Continuous Integration

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    uses: mfscannell/reusable-workflows/.github/workflows/reusable-build.yml@master # or ./.github/workflows/reusable-build.yml
    with:
      dotnet_version: 9.0.x